# Generated by Django 2.1 on 2018-09-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='homepage/static/img')),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='homepage.Play')),
            ],
        ),
    ]
