# Generated by Django 2.1 on 2018-09-05 07:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayCasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PlayVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='idx',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='play',
            name='num_of_audience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playvideo',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='homepage.Play'),
        ),
        migrations.AddField(
            model_name='playcasting',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castings', to='homepage.Play'),
        ),
    ]
