# Generated by Django 2.1 on 2018-09-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20180905_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='poster',
            field=models.ImageField(upload_to='plays', verbose_name='포스터 이미지'),
        ),
    ]
