# Generated by Django 2.1 on 2018-09-05 15:30

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20180905_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='poster',
            field=models.ImageField(upload_to=homepage.models.play_poster_path, verbose_name='포스터 이미지'),
        ),
    ]
