# Generated by Django 2.1 on 2018-09-07 10:51

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_gala_galaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=homepage.models.gala_media_path, verbose_name='공연사진')),
                ('gala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='homepage.Gala')),
            ],
        ),
        migrations.RenameModel(
            old_name='GalaImage',
            new_name='GalaSetlist',
        ),
        migrations.RenameField(
            model_name='galasetlist',
            old_name='image',
            new_name='setlist',
        ),
    ]
