# Generated by Django 2.1 on 2018-09-09 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20180907_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('team', models.CharField(choices=[('기획', '기획'), ('무대', '무대'), ('배우', '배우'), ('연출', '연출'), ('음악', '음악'), ('안무', '안무(9기 이전)')], max_length=2, verbose_name='팀')),
                ('position', models.CharField(choices=[('공동대표', '공동대표'), ('회장', '회장'), ('부회장', '부회장'), ('팀장', '팀장'), ('팀원', '팀원')], default='팀원', max_length=6)),
                ('admission_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='학번')),
                ('major', models.CharField(max_length=10, verbose_name='학과')),
                ('admission_order_letme', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='기수')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=homepage.models.play_media_path, verbose_name='공연 준비 사진')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='group_photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=homepage.models.play_poster_path, verbose_name='단체사진'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playimage',
            name='image',
            field=models.ImageField(upload_to=homepage.models.play_media_path, verbose_name='공연 사진'),
        ),
        migrations.AddField(
            model_name='playphoto',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='homepage.Play'),
        ),
        migrations.AddField(
            model_name='playmember',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='homepage.Play'),
        ),
    ]
