# Generated by Django 2.1 on 2018-09-09 06:04

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20180909_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayRelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=homepage.models.play_media_path, verbose_name='공연 관련 사진')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_images', to='homepage.Play')),
            ],
        ),
        migrations.RemoveField(
            model_name='playphoto',
            name='play',
        ),
        migrations.DeleteModel(
            name='PlayPhoto',
        ),
    ]
