# Generated by Django 2.1 on 2018-09-09 11:57

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20180909_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayTeamPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_photo', models.ImageField(upload_to=homepage.models.play_media_path, verbose_name='팀별사진')),
                ('team', models.CharField(choices=[('임원', '회장단/대표단'), ('기획', '기획'), ('무대', '무대'), ('배우', '배우'), ('연출', '연출'), ('음악', '음악'), ('안무', '안무(9기 이전)'), ('대표', '대표'), ('임원', '임원')], max_length=2, verbose_name='팀')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamphotos', to='homepage.Play')),
            ],
        ),
        migrations.AlterField(
            model_name='playmember',
            name='team',
            field=models.CharField(choices=[('기획', '기획'), ('무대', '무대'), ('배우', '배우'), ('연출', '연출'), ('음악', '음악'), ('안무', '안무(9기 이전)')], max_length=6, verbose_name='팀'),
        ),
    ]
