# Generated by Django 2.1 on 2018-09-10 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20180910_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='playvideo',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='영상 이름'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playvideo',
            name='video_url',
            field=models.CharField(max_length=200, verbose_name='공연 관련 링크(극 공개, 티저, 인터뷰순 )'),
        ),
    ]
