# Generated by Django 2.1 on 2018-09-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20180910_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playvideo',
            name='video_url',
            field=models.CharField(max_length=200, verbose_name='공연 관련 링크(facebook viedo id, (극 공개, 티저, 인터뷰순으로 입력))'),
        ),
    ]
